var data_root="data/",content_xml_link="data/content.xml?v=1",_data,_animated,_loaded,_title="",content_xml=null,curent_post_dir="",gallerysInfo=[],youtubeIDs=[],startSection=5,curentLocHash="";$(document).ready(function(){jqsetup();showLoadingAnimation();$.get(content_xml_link,"",onGetContentXml);curentLocHash=document.location.hash;setInterval("checkLocHash()",200);initFC()});function initLB(){}
function jqsetup(){$.ajaxSetup({error:function(a,b){a.status==0?alert("You are offline!!\n Please Check Your Network."):a.status==404?(document.location.hash="",document.location.reload()):a.status==500?(document.location.hash="",document.location.reload()):b=="parsererror"?alert("Error.\nParsing JSON Request failed."):b=="timeout"?alert("Request Time out."):alert("Unknow Error.\n"+a.responseText)}})}
function onGetContentXml(a){content_xml=a;loadMainMenu();loadLocHashPage()||(loadDefaultPage(),hideLoadingAnimation())}function loadLocHashPage(){var a=document.location.hash;if(a!=""&&(a=a.substring(1).split("/"),parseInt(a[1])))if(a[0]=="s")return loadSectionPage(a[1]),!0;else if(a[0]=="p")return loadFullPage(a[1]),!0;return!1}
function loadMainMenu(){var a=$("#hmenu"),b="";$(content_xml).find("section").each(function(){b="";if($(this).attr("type")=="post"){var c=$(this).find("post:eq(0)");c&&(b="<li><a onclick=\"loadFullPage('"+$(c).attr("id")+"')\">"+$(c).attr("title")+"</a></li>")}else if(b=$('<li><a onclick="loadSectionPage('+$(this).attr("id")+')">'+$(this).attr("title")+"</a></li>"),$(this).attr("submenu")=="true"){var d=$("<ul></ul>");$(this).find("post").each(function(){d.append("<li><a onclick=\"loadFullPage('"+
$(this).attr("id")+"')\">"+$(this).attr("title")+"</a></li>")});d.append('<div id="top_menu_shadow"></div>');b.append(d)}a.append(b)})}function loadDefaultPage(){$("#main_data").html("");$("#curent_menu").hide();loadSectionPage(startSection)}function checkLocHash(){if(curentLocHash!=document.location.hash)curentLocHash=document.location.hash,loadLocHashPage()}function setLocationHash(a){document.location.hash=a;curentLocHash=document.location.hash}
function loadSectionPage(a){setLocationHash("s/"+a);a=$("section[id='"+a+"']",content_xml);if(a.attr("type")=="post")a=a.find("post:eq(0)"),loadFullPage($(a).attr("id"));else{_animated=_loaded=!1;hidePage();loadSidebar(a);var b='<div id="main_data_header"><h2><b>'+a.attr("title")+"</b></h2><hr/></div>";$(a).children("post").each(function(){var a=$(this).attr("id"),d=$(this).attr("dir");$(this).find("tizer").each(function(){var f=$(this).children("image");b+=getTizer($(this).attr("title"),a,$(this).children("text").text(),
d+$(f).attr("mini"),d+$(f).attr("full"),$(f).attr("height"),$(f).attr("width"));b+="<br/>"})});_data=b;_loaded=!0;show_dataIfLoaded()}}
function getTizer(a,b,c,d,f,e,g){var h="";if(d!=null&&d!=""){if(f==null||f=="")f=d;h=e&&g?'<a class="gallery" href="'+data_root+f+'"><img class="proj_title_img" src="'+data_root+d+'" alt="" '+(' style="height: '+e+"px; width: "+g+'px;" ')+" /></a>":'<a class="gallery" href="'+data_root+f+'"><img class="proj_title_img" src="'+data_root+d+'" alt="" /></a>'}return'<div class="rounded"><div class="tizer"><div class="tizer_header"><a onclick="loadFullPage('+b+')"><h3>'+a+'</h3></a></div><div class="tizer_body">'+
h+c+'<br/><a class="more" onclick="javascript:loadFullPage('+b+')">\u043f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435...</a></div></div></div>'}
function loadFullPage(a){setLocationHash("p/"+a);youtubeIDs=[];gallerysInfo=[];post=$("post[id='"+a+"']",content_xml);curent_post_dir=post.attr("dir");section=$(post).parent();full_xml_link=data_root+curent_post_dir+$(post).attr("xmlcontent");_animated=_loaded=!1;hidePage();_title=$(post).attr("title");loadSidebar(section);$.get(full_xml_link,"",onGetFullPageXml)}
function loadSidebar(a){$("#sidebar_right").animate({opacity:"hide"},200,function(){loadMenu(a);loadContacts()}).animate({opacity:"show"},300,initializeBtns)}
function loadMenu(a){if(a!=null&&a!=""&&$(a).attr("submenu")=="true"){var b='<ul class="cssmenu">',c=$(a).attr("title");$(a).children("post").each(function(){b+="<li><a onclick=\"javascript:loadFullPage('"+$(this).attr("id")+"')\">"+$(this).attr("title")+"</a></li>"});b+="</ul>";a='<div class="rounded"><div id="rounded_body" class="left_menu"><div id="sidebar_right_menu1_head"><h4 onclick="loadSectionPage('+$(a).attr("id")+')">'+c+"</h4></div>"+b+'</div></div><div class="rounded_bottom"><div class="left_bottom_rounded"></div><div class="fill_bottom_rounded"></div><div class="right_bottom_rounded"></div></div>';
$("#curent_menu").html(a);$("#curent_menu").show()}else $("#curent_menu").hide()}
function loadContacts(){$("#contacts").html()==""&&($("#contacts").hide(),$("#contacts").html('<div class="rounded printObj"><div id="rounded_body"><div id="sidebar_right_menu1_head"><h4 class="printTitle">\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435<img title="\u0412\u0435\u0440\u0441\u0438\u044f \u0434\u043b\u044f \u043f\u0435\u0447\u0430\u0442\u0438" style="float: right;" class="printBtn opacityOnOver" src="pic/printer.png"/></h4></div><div class="tizer_body printData"><table><tbody><tr><td style="width: 40%;"><b>\u0418\u043c\u044f: </b></td><td>\u0412\u043b\u0430\u0434\u0438\u043c\u0438\u0440 \u0421. \u0421\u0443\u0441\u0435\u0432</td><tr><td><b>\u0421\u0430\u0439\u0442-\u0432\u0438\u0437\u0438\u0442\u043a\u0430: </b></td><td><a href="http://g1ts.net/">http://g1ts.net</a></td><tr><td><b>Email: </b></td><td><span><a href="mailto:work@g1ts.net">work@g1ts.net</a>, (<a href="mailto:g1ts.work@ya.ru">g1ts.work@ya.ru</a>)</span></td><tr><td><b>Skype: </b></td><td>g1ts.net</td><tr><td><b>XMPP (JabberID): </b></td><td><span style="display: block;">g1ts.work@jabber.ru, g1ts.work@jabber.org</span></td></tbody></table></div></div></div><div class="rounded_bottom"><div class="left_bottom_rounded"></div><div class="fill_bottom_rounded"></div><div class="right_bottom_rounded"></div></div><div id="modal-mailme-content"><iframe id="mailmeframe" src="mailme/mailme.php"></iframe></div>'),$("#contacts").animate({opacity:"show"},
400))}function onGetFullPageXml(a){content=$("content",a);_data=getFullPage(content);_loaded=!0;show_dataIfLoaded()}
function updateLB(){settings={imageLoading:"pic/lb/lightbox-ico-loading.gif",imageBtnPrev:"pic/lb/lightbox-btn-prev.gif",imageBtnNext:"pic/lb/lightbox-btn-next.gif",imageBtnClose:"pic/lb/lightbox-btn-close.gif",imageBlank:"pic/lb/lightbox-blank.gif"};$(function(){for(var a in gallerysInfo)$("a.gallery_"+gallerysInfo[a].galleryID).lightBox(settings);$("a.gallery").lightBox(settings)})}
function getFullPage(a){var b='<div id="main_data_header"></div>';_title!=null&&_title!=""&&(b='<div id="main_data_header"><h2 class="printTitle"><b>'+_title+"</b></h2><hr/></div>");b+='<div class="rounded printObj"><div class="tizer">';var c=$(a).attr("title");b+=c&&$.trim(c)!=""?'<div class="tizer_header"><h3 class="printTitle">'+c+'<div class="hbtns"><img title="\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c \u0432\u0441\u0435" class="expandAll opacityOnOver" src="pic/spoiler/0011.png"/><img title="\u0421\u0432\u0435\u0440\u043d\u0443\u0442\u044c \u0432\u0441\u0435" class="hideAll opacityOnOver" src="pic/spoiler/0021.png"/><img title="\u0412\u0435\u0440\u0441\u0438\u044f \u0434\u043b\u044f \u043f\u0435\u0447\u0430\u0442\u0438 (\u043e\u0442\u043b\u044c\u043a\u043e \u0440\u0430\u0441\u043a\u0440\u044b\u0442\u0435 \u0441\u043f\u043e\u0439\u043b\u0435\u0440\u044b)" class="printBtn opacityOnOver" src="pic/printer.png"/></div></h3></div><div class="tizer_body printData">':
'<div class="tizer_body printData"><div class="hbtns"><img title="\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c \u0432\u0441\u0435" class="expandAll opacityOnOver" src="pic/spoiler/0011.png"/><img title="\u0421\u0432\u0435\u0440\u043d\u0443\u0442\u044c \u0432\u0441\u0435" class="hideAll opacityOnOver" src="pic/spoiler/0021.png"/><img title="\u0412\u0435\u0440\u0441\u0438\u044f \u0434\u043b\u044f \u043f\u0435\u0447\u0430\u0442\u0438 (\u043e\u0442\u043b\u044c\u043a\u043e \u0440\u0430\u0441\u043a\u0440\u044b\u0442\u0435 \u0441\u043f\u043e\u0439\u043b\u0435\u0440\u044b)" class="printBtn opacityOnOver" src="pic/printer.png"/></div>';
b+=getTopImage(a)+getPageText($(a).children("text"))+getPageFeatures($(a).children("features"))+getPageCarousels($(a).find("images > set"))+getYoutubePlayers($(a).children("videos"))+getLinks($(a).children("links"))+"</div></div></div>";return b}
function getTopImage(a){a=$(a).find("images > topimage");if(a.length>0){var b='<a class="gallery" href="'+data_root+curent_post_dir+a.attr("full")+'"><img class="proj_title_img"';a.attr("height")&&a.attr("width")&&(b+='style="height: '+a.attr("height")+"px; width: "+a.attr("width")+'px;"');b+=' src="'+data_root+curent_post_dir+a.attr("mini")+'" alt="" /></a>';return b}return""}
function getPageText(a){var b="";$(a).children("p").each(function(){b+='<p class="pagetext">';b+=$(this).text();b+="</p>"});return b}
function getPageFeatures(a){var b="",c="",d="";$(a).children("group").each(function(){c=$(this).attr("title")||"";d=$(this).attr("type")||"listKV";if(c!=""){b+='<div class="features_div">';var a="";if(d=="listKV")a='<ul class="project_info">',$(this).children("feature").each(function(){a+="<li><b>";var b=$(this).attr("title");b&&b!=""&&(a+=b+":");a+=" </b>"+($(this).attr("value")||"")+($(this).text()||"")+"</li>"}),a+='</ul><div class="clear"></div>';else if(d=="list"){a='<ul class="project_info">';
var e;$(this).children("feature").each(function(){e=$(this).attr("title")||"";e!=""&&(e+=" ");e+=$(this).attr("value")||"";e!=""&&(e+=" ");e+=$(this).text()||"";a+="<li>"+e+"</li>"});a+='</ul><div class="clear"></div>'}else d=="text"&&(a="",$(this).children("feature").each(function(){e=$(this).attr("value")||"";a+='<p class="featureText">';var b=$(this).attr("title")||"";b!=""&&(a+="<b>"+b+"</b><br/>");a+=e+$(this).text()+"</li>"}),a+='<div class="clear"></div>');a+=getPageFeatures(this);b+=wrapInSpoiler(a,
c);b+="</div>"}});b!=""&&(b='<div id="features_div">'+b+"</div>");return b}function show_dataIfLoaded(){_loaded==!0&&_animated==!0?(hideLoadingAnimation(),$("#main_data").html(_data),$("#main_data").fadeIn(300),$.scrollTo(0),updateScripts()):_loaded==!0&&_animated==!1||_loaded==!1&&_animated==!0&&showLoadingAnimation()}function hidePage(){$("#main_data").fadeOut(200,function(){_animated=!0;show_dataIfLoaded()})}function showLoadingAnimation(){$("#main").addClass("loading")}
function hideLoadingAnimation(){$("#main").removeClass("loading")}
function getPageCarousels(a){var b="",c=$(a).attr("title")||"\u0421\u043a\u0440\u0438\u043d\u0448\u043e\u0442\u044b",d="",f=0,e=[],g=null,h=null;$(a).children("group").each(function(){e=[];f+=1;d=$(this).attr("title")||c;g=$(this).attr("height");h=$(this).attr("width");$(this).find("image").each(function(){e.push(new imageFile($(this).attr("mini"),$(this).attr("full"),$(this).attr("title")))});b+=wrapInSpoiler(getCarouse(e,null,f,g,h),d)});b!=""&&(f>1&&(b=wrapInSpoiler(b,c)),b='<div id="carouses_div">'+
b+"</div>");return b}function imageFile(a,b,c){this.mini=a||"";this.full=b||"";this.title=c||""}function getSimpleCarouses(){var a="",b=[];b.push(1);b.push(2);for(var c in b)a+=wrapInSpoiler(getSimpleCarouse1(7,b[c]));return wrapInSpoiler(a,"\u0421\u043a\u0440\u0438\u043d\u0448\u043e\u0442\u044b")}function getSimpleCarouse1(a,b,c){var d=10;a>0&&(d=a);a=[];for(var f=0;f<d;f++)a.push({mini:"1_mini.jpg",full:"1_full.jpg"});return getCarouse(a,c,b)}
function galleryInfo(a,b){this.galleryID=a||gallerysInfo.length+1;this.count=b||0}
function getCarouse(a,b,c,d,f){var e='<div class="clear"></div>';gallerysInfo.push(new galleryInfo(c,a.length));e+='<div class="jcl_c_h">';b&&(e+="<b>"+b+": </b><br/>");e+='<div class="myjCarousel_wrap">';e+='<div class="carousel_container_'+c+'">';e+='<ul class="carousel_content">';b=0;for(var g in a)b+=1,e+=d&&f?'<li class="carousel_item" style="height: '+d+"px; width: "+f+'px;"><a class="gallery_'+c+'" href="'+data_root+curent_post_dir+a[g].full+'"><img class="myjCarousel_img" src="'+data_root+
curent_post_dir+a[g].mini+'" alt="" /></a></li>':'<li class="carousel_item"><a class="gallery_'+c+'" href="'+data_root+curent_post_dir+a[g].full+'"><img class="myjCarousel_img" src="'+data_root+curent_post_dir+a[g].mini+'" alt="" /></a></li>';e+="</ul>";e+="</div>";e+="</div>";b>3&&(e+='<div class="carouselBtns">',e+='<button id="carousel_prev_btn_'+c+'"><<</button>',e+='<button id="carousel_next_btn_'+c+'">>></button>',e+="</div>");e+="</div>";return e}
function activateCarouse(){for(var a in gallerysInfo)initializeJCL(gallerysInfo[a])}function initializeJCL(a){var b=a.count,c=!0;b>7?b=7:b<=3?(b=3,c=!1):b-=1;$(".carousel_container_"+a.galleryID).jCarouselLite({btnNext:"#carousel_next_btn_"+a.galleryID,btnPrev:"#carousel_prev_btn_"+a.galleryID,mouseWheel:!0,vertical:!1,circular:c,visible:b})}
function getSimpleYoutubePlayers(){var a='<div id="utvideos">';a+=wrapInSpoiler(getYoutubePlayer("ylLzyHk54Z0"),"\u0412\u0438\u0434\u0435\u043e1");a+=wrapInSpoiler(getYoutubePlayer("ylLzyHk54Z0"),"\u0412\u0438\u0434\u0435\u043e2");a+="</div>";return wrapInSpoiler(a,"\u0412\u0438\u0434\u0435\u043e")}
function getYoutubePlayers(a){var b=0,c=0,d='<div id="utvideos">',f="",e="";$(a).children("group").each(function(){c=0;f="";e=$(this).attr("title")||"\u0412\u0438\u0434\u0435\u043e "+(b+1);$(this).find("video").each(function(){$(this).attr("type")=="youtube"&&(f+=getYoutubePlayer($(this).attr("vid")),c+=1)});c>0&&(d+=wrapInSpoiler(f,e),b+=1)});b>1&&(d=wrapInSpoiler(d,"\u0412\u0438\u0434\u0435\u043e"));d+="</div>";if(b>0)return d;return""}
function getYoutubePlayer(a){a={id:a,width:480,height:295};youtubeIDs.push(a);return'<div style="width: '+a.width+"px; height: "+a.height+'px;" class="youtubePlayerDiv"><div id="youtubePlayerDiv_'+(youtubeIDs.length-1)+'">Loading...</div></div>'}function initializeVideos(){youtubeIDs.length>0&&initializeYoutubePlayers()}function initializeYoutubePlayers(){onLoadSwfobjectCallback()}
function onLoadSwfobjectCallback(){for(var a in youtubeIDs){var b="youtubePlayerDiv_"+a,c=youtubeIDs[a];swfobject.embedSWF("http://www.youtube.com/v/"+c.id+"&enablejsapi=1&rel=0&autoplay=0&border=1&fs=0",b,c.width,c.height,"9",null,null,{allowScriptAccess:"always",wmode:"opaque"},{id:b+"_Player"})}}function myLink(a,b,c){this.title=a||"";this.link=b||"";this.type=c||"extern"}
function getSimpleLinks(){var a=[new myLink("\u0421\u0441\u044b\u043b\u043a\u04301","http://www.trg"),new myLink("\u0421\u0441\u044b\u043b\u043a\u04302","http://www.trg")];return wrapInSpoiler(getLinksDiv(a),"\u0421\u0441\u044b\u043b\u043a\u0438")}
function getLinks(a){var b=0,c=0,d=[],f="";$(a).children("group").each(function(){c=0;d=[];$(this).find("link").each(function(){d.push(new myLink($(this).attr("title"),$(this).attr("href")));c+=1});c>0&&(f+=wrapInSpoiler(getLinksDiv(d),$(this).attr("title")),b+=1)});b>1&&(f=wrapInSpoiler(f,"\u0421\u0441\u044b\u043b\u043a\u0438"));if(b>0)return f;return""}
function getLinksDiv(a){var b='<div class="linksDiv">',c;for(c in a){var d=a[c];b+="<b>"+d.title+':</b> <a href="'+d.link+'" target="_blank">\u0441\u0441\u044b\u043b\u043a\u0430</a><br/>'}b+="</div>";return b}function wrapInSpoiler(a,b){var c='<div class="spoiler_wrap">';c+='<div class="spoiler_head">'+(b||"Spoiler")+"</div>";c+='<div class="spoiler_body">'+a+'<div class="clear"></div></div>';c+="</div>";return c}
function initializeSpoilers(){var a=$(".spoiler_wrap");a.children(".spoiler_head").toggleClass("spoiler_head_hide");a.children(".spoiler_body").hide();$(".spoiler_head").click(function(){$(this).toggleClass("spoiler_head_hide");var a=$(this).parent();$(a).children(".spoiler_body").slideToggle("show");return!1});$(".spoiler_head").length>0?($("img.expandAll").click(function(){$(".spoiler_head.spoiler_head_hide!").click()}),$("img.hideAll").click(function(){$(".spoiler_head").not(".spoiler_head_hide").click()})):
($("img.hideAll").hide(),$("img.expandAll").hide())}var printWindow;
function initializeBtns(){$(".opacityOnOver").mouseover(function(){$(this).queue("fx").length>1&&$(this).dequeue();$(this).stop().animate({opacity:1},100)});$(".opacityOnOver").mouseout(function(){$(this).queue("fx").length>1&&$(this).dequeue();$(this).stop().animate({opacity:0.6},100)});$(".printBtn").unbind("click");$(".printBtn").click(function(){var a=$(this).closest(".printObj"),b=a.find(".printTitle").text()||"";b==""&&(b=$("#main_data_header > .printTitle").text());printWindow&&printWindow.close();
printWindow=window.open("print.html",b,"width=800,height=600,toolbar=no,status=no,scrollbars=yes,menubar=yes");printWindow.printData=a.find(".printData").clone().html();printWindow.printTitle=b});initSM()}function updateScripts(){initializeVideos();activateCarouse();updateLB();initializeSpoilers();initializeBtns();initSM()}
function hmenuhover(){if(document.getElementById("hmenu"))for(var a=document.getElementById("hmenu").getElementsByTagName("LI"),b=0;b<a.length;b++)a[b].onmouseover=function(){this.className+=" iehover"},a[b].onmouseout=function(){this.className=this.className.replace(/ iehover\b/,"")}}window.attachEvent&&window.attachEvent("onload",hmenuhover);
$(function(){$(window).scroll(function(){$(window).scrollTop()>=115?($("#head-bar").css("top",-1),$("#head-bar").css("position","fixed")):($("#head-bar").css("top",""),$("#head-bar").css("position",""));$(window).scrollTop()>=130?($("#sidebar_right").css("top",39),$("#sidebar_right").css("position","fixed")):($("#sidebar_right").css("top",""),$("#sidebar_right").css("position",""))})});
function getCookie(a){val=null;for(var b=document.cookie.split(";"),c=0;c<b.length;c++){var d=jQuery.trim(b[c]);if(d.substring(0,a.length+1)==a+"="){val=decodeURIComponent(d.substring(a.length+1));break}}return val}
function initFC(){var a=$('<img class="opacityOnOver" onClick="javascript:toggleHead();" src="pic/re.png"/>');$("#headControlPanel").append(a);fc=$("#fcon");sht=$("#staticHeadText");w=$("#wrapper");cc=$("#ccursor");ll=getCookie("ll");document.cookie="ll="+new Date;getCookie("hideFC")=="true"&&(fc.hide(),sht.show());fillHeadFC()}var canToggleCC=!0;function updateCC(){sht=$("#staticHeadText");canToggleCC?cc.toggle():cc.hide()}
function toggleHead(){fc.is(":visible")?(fc.fadeOut(300,function(){sht.fadeIn(300)}),document.cookie="hideFC=true"):(sht.fadeOut(300,function(){fc.fadeIn(300)}),document.cookie="hideFC=false")}function fillHeadFC(){var a=getCookie("ll");cc.before("Welcome to g1ts.net!<br>No mail.<br>");a?cc.before("Last login: "+a+"<br>"):cc.before("Last login: "+new Date+"<br>");cc.before("anonymous@g1ts.net:~$ ");setInterval("updateCC()",600)}
function initSM(){$("#modal-mailme").unbind("click");$("#modal-mailme").click(function(){$("#modal-mailme-content").modal({onOpen:function(a){a.overlay.fadeIn("fast",function(){a.data.hide();a.container.slideDown("fast",function(){a.data.fadeIn("slow")})})},onClose:function(a){a.data.fadeOut("fast",function(){a.container.slideUp("fast",function(){a.overlay.fadeOut("slow",function(){$.modal.close()})})})}});return!1})};
